export const REGRAS_COMISSAO: Record<string, Record<string, number>> = {
  "Alan Robson de Oliveira": {
    consulta_base: 80,
    protocolo_atendimento: 40,
    protocolo_prescricao: 0.3,
    outros_protocolos: 0.1,
    calorimetria: 0.3,
  },
  "Luciana Eloia Quintino da Silva": {
    consulta_plano: 50,
    consulta_protocolo: 50,
    protocolo_prescricao: 0.2,
    calorimetria: 0.3,
    enzimas: 100,
  },
  "Ingryd Victor Girão": {
    consulta_plano: 50,
    consulta_protocolo: 50,
    protocolo_prescricao: 0.2,
    calorimetria: 0.3,
  },
  "Karen Stefani Costa Portela": {
    consulta_plano: 50,
    consulta_protocolo: 50,
    protocolo_prescricao: 0.2,
    calorimetria: 0.3,
  },
  "Pedro Victor de Sousa Teles": {
    consulta_plano: 50,
    consulta_protocolo: 50,
    protocolo_prescricao: 0.2,
    calorimetria: 0.3,
  },
  "Rayana Menezes Pinto": {
    consulta_plano: 50,
    consulta_protocolo: 50,
    protocolo_prescricao: 0.2,
    calorimetria: 0.3,
  },
  "André Vyann Ramalho Guanabara Araujo": {
    reembolso: 0.3,
    protocolo_injetavel: 0.7,
    implante: 0.3,
  },
  "Átila Ribeiro": {
    reembolso: 0.3,
    protocolo_injetavel: 0.7,
    implante: 0.3,
    turno: 200,
  },
  "José Lucena": { reembolso: 0.3, protocolo_injetavel: 0.7, implante: 0.3 },
  "Melissa Ciríaco Ribeiro": {
    fixo: 2400,
    protocolo_injetavel: 0.3,
    mounjaro_importado: 0.2,
    mounjaro_manipulado: 0.3,
    protocolo_slim: 0.3,
  },
  "Luana Cajado Lima de Oliveira": {
    fixo: 1840,
    mounjaro_importado: 0.2,
    mounjaro_manipulado: 0.3,
    consulta: 0.8,
    protocolo_injetavel: 0.3,
    implante: 0.1,
  },
  "Catarina Ribeiro Moreno": {
    consulta: 0.8,
    mounjaro_importado: 0.2,
    mounjaro_manipulado: 0.3,
    protocolo_injetavel: 0.3,
    implante: 0.3,
  },
};
